### ISSUE TITLE
KB5 bolometers should have their corresponding meshes set as camera_geometry

### ISSUE THREAD

**Issue by jacklovell** [cherab/jet#11]
There are KB5V and KB5H mesh files available, but these are not loaded when `load_kb5_camera` is called. At the moment, they are loaded manually in the sensitivity and etendue calculation demos.

Observations using these cameras will only be meaningful if the mesh geometry is loaded, so it should be loaded along with the slits and foils and not left to the end user to do.

**Comment by mattngc** [comment]
Fixed in PR #12
