### ISSUE TITLE
_find_nearest of JETEquilibrium crash when value is between (array[-2], array[-1])

### ISSUE THREAD

**Issue by Mateasek** [cherab/jet#27]
[_find_nearest](https://github.com/cherab/jet/blob/70b845cc0bac6fa4a92159805a253938cad775b1/cherab/jet/equilibrium/equilibrium.py#L184) will crash, if the value is between (array[-2], array[-1]), the reason is [index = np.searchsorted(array, value, side="left")](https://github.com/cherab/jet/blob/70b845cc0bac6fa4a92159805a253938cad775b1/cherab/jet/equilibrium/equilibrium.py#L189) will  make index to be the last index of the array, which results in IndexError on the following line (array[index + 1]).

I would suggest replacing this with simple:
`index = np.argmin(np.abs(array - value))`
It might be slower, but here the speed is not crucial and it works for any array.

Another possibility would be to add some condition for index and array shape.

**Comment by jacklovell** [comment]
Fixed by #28
